In [3]:
import numpy as np
print(np.__version__)

1.26.4


In [5]:
# 1.NumPy is a Python library used for working with arrays.
#2.NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
# 3.he array object in NumPy is called ndarray, it provides a lot of supporting functions that make workingwith ndarray very easy.
# Arrays: The array object in NumPy is called ndarray
    # create a NumPy ndarray object by using the array() function
    #nested array: are arrays that have arrays as their elements.
    # A, An array that has 0-D arrays is called uni-dimensional or 1-D =  np.array([1, 2, 3, 4, 5])
    # B, An array that has 1-D arrays is called 2-D = np.array([[1, 2, 3], [4, 5, 6]])
    # C, An array that has 2-D arrays is called 3-D = np.array([[[1, 2, 3], [4, 5, 6]], [7, 8, 9]]])
   
#4 we can Check how many dimensions the arrays have: using print(a.ndim)
#5 When the array is created, you can define the number of dimensions by using the ndmin argument
#6 You can access an array element by referring to its index number
    #1-D: print([1])
    #2-D: print([0,1]) think array like table. 0 =row and 1=column 
#7 shape is numphy attribute means changing the shape of an array (number of elements in each dimension).
    #By reshaping we can add or remove dimensions or change number of elements in each dimension.
    #Example Convert the following 1-D array with 12 elements into a 2-D array.
#8 Searching: To search an array, use the where() method.  4, 5, 4, 4]) x = np.where(arr == 4)
    # Find the indexes where the values are even: x = np.where(arr%2 == 0)
#9 Generate a random integer x = random.randint(100)
   # Generate Random Float = x = random.rand()
# Generate Random Array = x=random.randint(100, size=(5))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
import numpy as np
arr = np.array(42)
print(arr)

42


In [9]:
arr0 = np.array([1, 2, 3, 4, 5])
print(arr0)

[1 2 3 4 5]


In [37]:
import numpy as np

arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)


[[1 2 3]
 [4 5 6]]


In [39]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [47]:
# Check how many dimensions the arrays have:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
print(a.ndim)
print(b.ndim)

0
1


In [66]:
# When the array is created, you can define the number of dimensions by using the ndmin argument
arr = np.array([1,2,3], ndmin=5)
print(arr)
print(arr.ndim)

[[[[[1 2 3]]]]]
5


In [74]:
# You can access an array element by referring to its index number
arr = ([1, 2, 3, 4, 5])
print(arr[0])

1


In [76]:
 #2-D: print([0,1]) think array like table. 0 =row and 1=column 

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [88]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:3])

[2 5]


In [80]:
print(arr[::2])

[1 3 5 7]


In [96]:
#Example Convert the following 1-D array with 12 elements into a 2-D array.Example
#Convert the following 1-D array with 12 elements into a 2-D array.
# The outermost dimension will have 4 arrays(row), each with 3 elements(column)
    
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [102]:
#To search an array, use the where() method.
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6]),)


In [106]:
x = np.where(arr%2 == 0)
print(x)

(array([1, 3, 5, 6]),)
